//! 编辑器领域命令规范声明。

use crate::command::kind::{Buildability, CommandKind, CommandKindSpec};
use crate::{CommandInvocation, EditorAction};

pub const SPECS: &[CommandKindSpec] = &[
    CommandKindSpec::new(
        CommandKind::EditorInsertText,
        "editor.insert_text",
        "Insert Text",
        "Insert provided text at the current caret position.",
        Buildability::RequiresArgs,
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorInsertNewline,
        "editor.insert_newline",
        "Insert Newline",
        "Insert a newline at the current caret position.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::InsertNewline)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveLeft,
        "editor.move_left",
        "Move Left",
        "Move the caret one character to the left.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveLeft)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveRight,
        "editor.move_right",
        "Move Right",
        "Move the caret one character to the right.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveRight)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveUp,
        "editor.move_up",
        "Move Up",
        "Move the caret one line up.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveUp)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveDown,
        "editor.move_down",
        "Move Down",
        "Move the caret one line down.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveDown)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveToStart,
        "editor.move_to_start",
        "Move To Start",
        "Move the caret to the beginning of the current line.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveToStart)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMoveToEnd,
        "editor.move_to_end",
        "Move To End",
        "Move the caret to the end of the current line.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MoveToEnd)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMovePageUp,
        "editor.page_up",
        "Page Up",
        "Move the caret one page up.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MovePageUp)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorMovePageDown,
        "editor.page_down",
        "Page Down",
        "Move the caret one page down.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::MovePageDown)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorDeleteBackward,
        "editor.delete_backward",
        "Delete Backward",
        "Delete one character backward.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::DeleteBackward)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorDeleteForward,
        "editor.delete_forward",
        "Delete Forward",
        "Delete one character forward.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::DeleteForward)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorDeleteWordBackward,
        "editor.delete_word_backward",
        "Delete Word Backward",
        "Delete one word backward.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::DeleteWordBackward)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorDeleteWordForward,
        "editor.delete_word_forward",
        "Delete Word Forward",
        "Delete one word forward.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::DeleteWordForward)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorUndo,
        "editor.undo",
        "Undo",
        "Undo the most recent edit.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::Undo)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorRedo,
        "editor.redo",
        "Redo",
        "Redo the most recently undone edit.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::Redo)),
        &[],
    ),
    CommandKindSpec::new(
        CommandKind::EditorSelectAll,
        "editor.select_all",
        "Select All",
        "Select all content in the current editor.",
        Buildability::Static(|| CommandInvocation::from(EditorAction::SelectAll)),
        &[],
    ),
];
