use crate::command::catalog::{CommandKey, CommandSpec};
use crate::{Command, EditorCommand};

pub const SPECS: &[CommandSpec] = &[
    CommandSpec::new(
        CommandKey::EditorInsertText,
        "editor.insert_text",
        "Insert Text",
        "Insert provided text at the current caret position.",
        || None,
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorInsertNewline,
        "editor.insert_newline",
        "Insert Newline",
        "Insert a newline at the current caret position.",
        || Some(Command::from(EditorCommand::InsertNewline)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveLeft,
        "editor.move_left",
        "Move Left",
        "Move the caret one character to the left.",
        || Some(Command::from(EditorCommand::MoveLeft)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveRight,
        "editor.move_right",
        "Move Right",
        "Move the caret one character to the right.",
        || Some(Command::from(EditorCommand::MoveRight)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveUp,
        "editor.move_up",
        "Move Up",
        "Move the caret one line up.",
        || Some(Command::from(EditorCommand::MoveUp)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveDown,
        "editor.move_down",
        "Move Down",
        "Move the caret one line down.",
        || Some(Command::from(EditorCommand::MoveDown)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveToStart,
        "editor.move_to_start",
        "Move To Start",
        "Move the caret to the beginning of the current line.",
        || Some(Command::from(EditorCommand::MoveToStart)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMoveToEnd,
        "editor.move_to_end",
        "Move To End",
        "Move the caret to the end of the current line.",
        || Some(Command::from(EditorCommand::MoveToEnd)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMovePageUp,
        "editor.page_up",
        "Page Up",
        "Move the caret one page up.",
        || Some(Command::from(EditorCommand::MovePageUp)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorMovePageDown,
        "editor.page_down",
        "Page Down",
        "Move the caret one page down.",
        || Some(Command::from(EditorCommand::MovePageDown)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorDeleteBackward,
        "editor.delete_backward",
        "Delete Backward",
        "Delete one character backward.",
        || Some(Command::from(EditorCommand::DeleteBackward)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorDeleteForward,
        "editor.delete_forward",
        "Delete Forward",
        "Delete one character forward.",
        || Some(Command::from(EditorCommand::DeleteForward)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorDeleteWordBackward,
        "editor.delete_word_backward",
        "Delete Word Backward",
        "Delete one word backward.",
        || Some(Command::from(EditorCommand::DeleteWordBackward)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorDeleteWordForward,
        "editor.delete_word_forward",
        "Delete Word Forward",
        "Delete one word forward.",
        || Some(Command::from(EditorCommand::DeleteWordForward)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorUndo,
        "editor.undo",
        "Undo",
        "Undo the most recent edit.",
        || Some(Command::from(EditorCommand::Undo)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorRedo,
        "editor.redo",
        "Redo",
        "Redo the most recently undone edit.",
        || Some(Command::from(EditorCommand::Redo)),
        &[],
    ),
    CommandSpec::new(
        CommandKey::EditorSelectAll,
        "editor.select_all",
        "Select All",
        "Select all content in the current editor.",
        || Some(Command::from(EditorCommand::SelectAll)),
        &[],
    ),
];
